### ISSUE TITLE
Is it intentional that two reviewers are required for a pull request?

### ISSUE THREAD

**Issue by kongslund** [ansible-collections/community.grafana#260]
I noticed that [.github/settings.yml](https://github.com/ansible-collections/community.grafana/blob/da7b0d223a23c0de7af593faffd10da1e2015ed5/.github/settings.yml) does not have anything declared for `main` but that for `master` and `devel` only 1 maintainer is needed for PR approvals.

That made me wonder if the current requirement of having two reviewers for a pull request is intentional or just due to a default behavior for a protected branch?

**Comment by rrey** [comment]
The settings.yml was created with the migration to collections and was never changed since then I think. It should probably be updated to remove master and devel that do not exists in this repo.

the goal is to have 2 reviewers to avoid having only one person reviewing, but I admit that lately I have been alone doing it.

**Comment by kongslund** [comment]
Having >=2 reviewers for a PR is certainly a good idea. Right now though, it looks as if you are the only maintainer that is active. The other auto-assigned reviewer has been inactive since February.

I'd be happy to assist with maintaining this project. There were also some maintainer volunteers in #217.

Is that a privilege you can grant or how does it work? It's not entirely clear to me after reading these guidelines:

* https://docs.ansible.com/ansible/latest/community/contributor_path.html#become-a-collection-maintainer
* https://docs.ansible.com/ansible/latest/community/maintainers_guidelines.html#how-to-become-a-maintainer

**Comment by rrey** [comment]
> I'd be happy to assist with maintaining this project. There were also some maintainer volunteers in https://github.com/ansible-collections/community.grafana/issues/217.

Any form of help is appreciated !
Volunteers started by processing the Issues and opened PR by doing reviews and creating patches.
If you want to start somewhere you can do the same.

I also. started to add a `help_needed` label on some issue, [here is the filtered issues](https://github.com/ansible-collections/community.grafana/labels/help_needed).
The most important one being https://github.com/ansible-collections/community.grafana/issues/220 because it would help better detect issues with modules (I think it is also valid for other modules and not only for the datasource one).

> Is that a privilege you can grant or how does it work? It's not entirely clear to me after reading these guidelines:
I don't think I can add people in the GitHub group that contains the project maintainers, I think a community manager can do that though and we'll just have to ask when time comes.
