### ISSUE TITLE
Version 1.6.0 is not available on Ansible Galaxy

### ISSUE THREAD

**Issue by csaba-sandor-toth** [ansible-collections/community.grafana#313]
##### SUMMARY

Version 1.6.0 is not available on Ansible Galaxy.
The latest available version on Ansible Galaxy is 1.5.4
Also in Releases  1.5.4 is displayed as latest ( despite 1.6.0 was released later)

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```
1.6.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by mariolenz** [comment]
@rrey You've tagged the 1.6.0 release. Any ideas?

**Comment by mariolenz** [comment]
@rrey Yep, I see it on [Galaxy](https://galaxy.ansible.com/ui/repo/published/community/grafana/?version=1.6.0). Thanks!

Maybe a good reason to close the issue ;-)

**Comment by mariolenz** [comment]
@rrey Out of curiosity: Is [grafana.grafana](https://github.com/grafana/grafana-ansible-collection) the successor of this collection and we can consider removing it from [the community package](https://pypi.org/project/ansible/)?

Or is this collection still maintained in parallel to grafana.grafana?

**Comment by rrey** [comment]
There was [an attempt to merge collections](https://github.com/ansible-community/community-topics/issues/212) but it failed because of the CLA requirement on Grafana side.

So both collections will remain.
The Grafana one has a focus on Grafana Cloud while the community one is for Grafana OSS.

Grafana may include OSS support in the future but we are not in talks anymore.
The community collection is unfortunately barely maintained as I am (mostly) the only active maintainer.

FYI I haven't worked on the collection for months.

**Comment by mariolenz** [comment]
Thanks for the information @rrey!

**Comment by rrey** [comment]
I leave you close the issue if everything is fine

**Comment by mariolenz** [comment]
> I leave you close the issue if everything is fine

I can't, don't have the permissions. But @csaba-sandor-toth can if the issue issue looks resovled.

**Comment by csaba-sandor-toth** [comment]
Version 1.6.0 and 1.6.1 are available on Ansible Galaxy
