### ISSUE TITLE
Importing dashboard to a certain folder

### ISSUE THREAD

**Issue by mrjoseph84** [ansible-collections/community.grafana#84]
##### SUMMARY

When using `grafana_dashboard` module, imported dashboard always lands in the main folder. It'd be useful to point a folder (e.g. by providing `folder_id`), where the dashboard should be imported.

##### ISSUE TYPE
- Feature enhancement (importing dashboards)

**Comment by mrjoseph84** [comment]
OK, I have just noticed in the source code that this was added in 2.10 - all you need to do is to provide a `folder: ` in my yml and it worked (so the issue can be closed). However, it seems that this has not been added to. the documentation yet: https://docs.ansible.com/ansible/latest/modules/grafana_dashboard_module.html

**Comment by rrey** [comment]
Hi @mrjoseph84 
You fall in a (hopefully) hole in the migration to collections. The documentation on the official Ansible Website is not yet the documentation from the Collection modules.

The code mentions that the change was introduced in 2.10 but the collections now leaves outside the Ansible Core versioning and the mention is here to avoid a test to fail in the CI (because the field is required).

@gundalow do you have any information regarding the documentation of collections being the source of the doc site ?
